Movies Example Application
==========================

Spring Data Neo4j was the first Spring Data project, started by the CEOs Rod Johnson and Emil Eifrem.
It enables convenient integration of Neo4j in your Spring-based application.
It provides object-graph mapping functionality and other features common to the Spring Data projects.


This repository shows how to use Neo4j Object Graph Mapper (OGM) and Spring Data Neo4j (SDN) on a simple movie domain.

There are following modules with example applications:

- `java-ogm` - implemented in Java and pure OGM. Exposing REST interface via JAX-RS.
- `java-spring-data-neo4j` - implemented in Java, Spring framework and Spring Data Neo4j. Exposing REST interface via Spring MVC.
- `java-spring-boot-spring-data-neo4j` - implemented in Java and Spring Boot. Exposing REST interface via Spring MVC.

This repository also contains other modules:

- `movies-domain` - entity classes for the movie domain
- `movies-test` - integration tests for the REST interface exposed by each application.


== Quickstart

See the readme file of each project for detailed instructions how to run it, but generally the process is as follows:

. http://neo4j.com/download[Download, install and start Neo4j Server].
. open the web-interface at http://localhost:7474
. configure a username and password if you haven't already.
. run `:play movies` command, and click and run the Cypher statement to insert the dataset
. clone this project from GitHub
. update `src/main/resources/application.properties` with the username and password you set above.
. run the project with `mvn jetty:run` or `mvn spring-boot:run`.
