Movies Example Application
==========================

This example application is implemented in Java and pure OGM.
It exposes REST interface via JAX-RS.

== Quickstart

. http://neo4j.com/download[Download, install and start Neo4j Server].
. open the web-interface at http://localhost:7474
. configure a username and password if you haven't already.
. run `:play movies` command, and click and run the Cypher statement to insert the dataset
. clone this project from GitHub
. update `java-ogm/src/main/resources/ogm.properties` with the username and password you set above.
. run the project with `mvn spring-boot:run`.


== Code Walkthrough

To use OGM add the following dependencies:

.pom.xml
[source,xml]
----
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm-core</artifactId>
    <version>${neo4j-ogm.version}</version>
</dependency>

<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm-bolt-driver</artifactId>
    <version>${neo4j-ogm.version}</version>
</dependency>
----

Annotate your `@NodeEntity` and `@RelationshipEntity`, you can use the OGM `Session` to access Neo4j APIs and object graph mapping functionality.

.Movie.java
[source,java]
----
@NodeEntity
public class Movie {

	@GraphId
	private Long id;

	private String title;

	private int released;

	private String tagline;

	@Relationship(type = "ACTED_IN", direction = Relationship.INCOMING)
	private List<Role> roles = new ArrayList<>();

}
----

Configure the `SessionFactory` and provide it as injectable:

.MoviesApplication.java
[source,java,indent=0]
----
SessionFactory sf = configureSessionFactoryUsingProperties();
// Register SessionFactory so it can be injected using @Context annotation
register(new AbstractBinder() {
    @Override
    protected void configure() {
        bind(sf);
    }
});
...
private SessionFactory configureSessionFactoryUsingProperties() {
    Configuration configuration = new Configuration.Builder(new ClasspathConfigurationSource("ogm.properties"))
            .build();

    return new SessionFactory(configuration, Movie.class.getPackage().getName());
}
----

Use the `SessionFactory` in services to access the database through the object mapper:

.MoviesService.java
[source,java]
----
@GET
@Path("/search")
@Produces(MediaType.APPLICATION_JSON)
public Movie findByTitle(@QueryParam("title") String title) {

    Session session = sessionFactory.openSession();
    try (Transaction tx = session.beginTransaction()) {
        Movie movie = single(session.query(Movie.class, "MATCH (m:Movie) WHERE m.title = {title} RETURN m",
                params("title", title)));

        tx.commit();
        return movie;
    }
}
----

== The Stack

These are the components of our Web Application:

* Application Type:         Java Web Application (Jetty)
* Web framework:            JAX-RS
* Persistence Access:       OGM
* Database:                 Neo4j-Server 3.x


